Adding support for (multiple) swift backends
salt-formulas/salt-formula-glance pull request #7
Opened 2017-05-08 14:40 UTC by mnederlof

Add support for swift_store_config_file setting and generating the references based on pillar data.

2017-05-10 11:46 UTC, mnederlof commented
This is the new way of managing swift, and also 'hides' the authentication credentials if direct url / locations are exposed via the glance API

2017-05-15 05:02 UTC, pupapaik commented
Just small adjustment with tests for mitaka to see validity of config.

2017-05-15 05:02 UTC, pupapaik requested changes

2017-05-15 05:02 UTC, pupapaik commented on tests/pillar/single_swift_references.sls
> +    version: liberty
Can you please add this test also for mitaka to verify that your config files does not have any syntax error?

2017-05-15 07:32 UTC, mnederlof commented
Updated the pillar test data

2017-05-15 07:46 UTC, merged