Add support for showing / returing multiple locations
salt-formulas/salt-formula-glance pull request #8
Opened 2017-05-09 14:26 UTC by mnederlof

2017-05-10 07:18 UTC, mnederlof commented
We are currently working on having a rbd backend and a swift backend. In order to do so, we needed these changes.

2017-05-15 05:05 UTC, pupapaik commented
Please resolve small adjustment. THanks

2017-05-15 05:05 UTC, pupapaik requested changes

2017-05-15 05:05 UTC, pupapaik commented on tests/pillar/single_multiple_backends.sls
> +    version: liberty
same here. Please put there version at least mitaka to see validity of config.

2017-05-15 07:33 UTC, mnederlof commented
Updated the pillar test data

2017-05-15 07:46 UTC, merged